import mysql.connector

listOfFacts = [[1, "The world’s oldest wooden wheel has been around for more than 5,000 years"],
               [2, "Sudan has more pyramids than any country in the world"],
               [3, "There are parts of Africa in all four hemispheres"],
               [4, "The world’s first animated feature film was made in Argentina"],
               [5, "German chocolate cake was invented in Texas"],
               [6, "The Philippines consists of 7,641 islands"],
               [7, "A one-way trip on the Trans-Siberian Railway involves crossing 3,901 bridges"],
               [8, "There’s enough gold inside Earth to coat the planet"],
               [9, "Cleveland was once the country’s fifth-largest city"],
               [10, "It takes a drop of water 90 days to travel the entire Mississippi River"],
               [11, "People once ate arsenic to improve their skin"],
               [12, "The first person processed at Ellis Island was a 15-year-old girl from Ireland"],
               [13, "Japan has one vending machine for every 40 people"],
               [14, "Lemons float, but limes sink"],
               [15, "McDonald’s once made bubblegum-flavored broccoli"],
               [16, "The first oranges weren’t orange"],
               [17, "A cow-bison hybrid is called a beefalo"],
               [18, "Scotland has 421 words for snow"],
               [19, "Samsung tests phone durability with a butt-shaped robot"],
               [20, "Peanuts aren’t technically nuts"],
               [21, "Armadillo shells are bulletproof"],
               [22, "Firefighters use wetting agents to make water wetter"],
               [23, "The longest English word is 189,819 letters long"],
               [24, "Kleenex tissues were originally intended for gas masks"],
               [25, "Blue whales eat half a million calories in one mouthful"],
               [26, "Most Disney characters wear gloves to keep animation simple"],
               [27, "The man with the world’s deepest voice can make sounds humans can’t hear"],
               [28, "Cows don’t have upper front teeth"],
               [29, "Bananas grow upside down"],
               [30, "There were active volcanoes on the moon when dinosaurs were alive"],
               [31, "Theodore Roosevelt had a pet hyena"],
               [32, "The CIA headquarters has its own Starbucks, but baristas don’t write names on the cups"],
               [33, "Giraffe tongues can be 20 inches long"],
               [34, "The inventor of the microwave appliance received only $2 for his discovery"],
               [35, "The Eiffel Tower can grow more than six inches during the summer"],
               [36, "Frankenstein’s Creature is a vegetarian"],
               [37, "Sloths have more neck bones than giraffes"],
               [38, "Bees can fly higher than Mount Everest"],
               [39, "Cap’n Crunch’s full name is Horatio Magellan Crunch"],
               [40, "Humans have jumped farther than horses in the Olympics"],
               [41, "The Terminator script was sold for $1"],
               [42, "Abraham Lincoln was a bartender"],
               [43, "Beethoven never knew how to multiply or divide"],
               [44, "The word “aquarium” means “watering place for cattle” in Latin"],
               [45, "An employee at Pixar accidentally deleted a sequence of Toy Story 2 during production"],
               [46, "Steve Jobs, Steve Wozniak, and Ron Wayne started Apple Inc. on April Fools’ Day"],
               [47, "The inventor of the tricycle personally delivered two to Queen Victoria"],
               [48, "Your brain synapses shrink while you sleep"],
               [49, "A waffle iron inspired one of the first pairs of Nikes"],
               [50, "Baseball umpires used to sit in rocking chairs"],
               [51, "The first commercial passenger flight lasted only 23 minutes"],
               [52, "The world’s first novel ends mid-sentence"],
               [53, "The French-language Scrabble World Champion doesn’t speak French"],
               [54, "The British Empire was the largest empire in world history"],
               [55, "Penicillin was first called “mold juice”"],
               [56, "The first stroller was engineered to be pulled by a goat (or animal of similar size)"],
               [57, "Neil Armstrong’s hair was sold in 2004 for $3,000"],
               [58, "Pregnancy tests date back to 1350 B.C.E."],
               [59, "Martin Luther King Jr. got a C in public speaking"],
               [60, "Bees can make colored honey"],
               [61, "Bananas glow blue under black lights"],
               [62, "The Pope can’t be an organ donor"],
               [63, "Red is the first color a baby sees"],
               [64, "Disneyland serves 2.8 million churros a year"],
               [65, "A lit candle creates 1 million tiny diamonds per second"],
               [66, "Flowers grow faster with music"],
               [67, "Mr. Potato Head was the first toy to be advertised on TV"],
               [68, "Camels have three eyelids"],
               [69, "Mosquitoes are attracted to people who just ate bananas"],
               [70, "Sonic the Hedgehog’s full name is Ogilvie Maurice Hedgehog"],
               [71, "The world’s termites outweigh the world’s humans about 10 to 1"],
               [72, "Most toilet paper solid in France is pink"],
               [73, "The human nose can remember 50,000 different scents"],
               [74, "Sliced bread was invented a year after the invention of TV"],
               [75, "If you keep a goldfish in a dark room, it will eventually turn white"],
               [76, "Bullfrogs do not sleep"],
               [77, "It took the creator of the Rubik’s Cube one month to solve the cube after he created it"],
               [78, "An ant’s sense of smell is stronger than a dog’s"],
               [79, "Alligators will give manatees the right of way if they are swimming near each other"],
               [80, "Sunsets on Mars are blue"],
               [81, "A one-day weather forecast requires about 10 billion math calculations"],
               [82, "People don’t sneeze in their sleep due to their brain shutting down the reflex"],
               [83, "The average American will eat 35,000 cookies in their lifetime"],
               [84, "Smelling apples or bananas can help you lose weight"],
               [85, "The hummingbird is the only bird that can fly backward"],
               [86, "Beavers were once the size of bears"],
               [87, "A pigeon’s feathers weigh more than their bones"],
               [88, "The spiked dog collar was invented by the ancient Greeks to protect their dogs from wolf attacks"],
               [89, "During World War II, Germany planned to collapse the British economy by dropping millions of counterfeit bills over London"],
               [90, "The youngest pope in history was Pope Benedict IX. He is also the only person to have been the pope more than once"],
               [91, "There is a town in Nebraska called Monowi with a population of one. The only resident is a woman who serves as mayor, bartender, and librarian."],
               [92, "The unique smell of rain actually comes from plant oils, bacteria, and ozone"],
               [93, "In 2016, Domino’s tested pizza delivery via reindeer in Japan"],
               [94, "Helen Keller is related to Robert E. Lee—her paternal grandfather was his second cousin"],
               [95, "Starfish don’t have blood. They circulate nutrients by using seawater in their vascular system"],
               [96, "Bubble wrap was originally invented to be a kind of plastic wallpaper"],
               [97, "Gummy bears were originally called 'dancing bears'"],
               [98, "Laughter synchronizes the brains of both speaker and listener so that they become emotionally attuned"],
               [99, "An oak tree produces about 10 million acorns during its lifetime"],
               [100, "There's enough concrete in the Hoover Dam to build a two-lane highway from San Francisco to New York City"],
               [101, 'The cortex gets its name from the Latin word for "bark" (of a tree).'],
               [102, 'There are approximately 86 billion neurons in the human brain.'],
               [103, 'The average human brain weighs about 3 pounds (1.4 kilograms).'],
               [104, 'Unlike humans, the octopus does not have a blind spot.'],
               [105, 'The average length of the adult spinal cord is 45 cm for men and 43 cm for women.'],
               [106, 'The skin of an adult human covers about 18-20 square feet (~2 square meters) and weighs about 6 lb (2.7 kg).'],
               [107, 'The sponge is the only multicellular animal without a nervous system.'],
               [108, 'The word "hypnosis" comes from the Greek word meaning "sleep."'],
               [109, 'A butterfly can taste with its feet.'],
               [110, 'The pufferfish, eaten as a delicacy in Japan, contains a potent neurotoxin called tetrodotoxin.'],
               [111, 'The heaviest human brain ever recorded weighed 5 lb., 1.1 oz (2.3 kg).'],
               [112, 'Stroke ("brain attack") is the 3rd leading cause of death in the US.'],
               [113, 'The Greek philosopher Aristotle believed that the heart, not the brain, was the seat of mental processes.'],
               [114, 'Information travels in the nerves at speeds up to 268 miles per hour (429 kilometers/hour).'],
               [115, 'An average yawn lasts about 6 seconds.'],
               [116, 'Most people dream about 5 times during each 8-hour period of sleep. Based on this number, people have about 1,825 dreams every year.'],
               [117, 'People can distinguish between 3,000 and 10,000 different smells.'],
               [118, 'Schizophrenia affects about 1 out of every 100 people.'],
               [119, 'Bees and butterflies can see ultraviolet light.'],
               [120, 'Sounds as loud as 130 dB can cause pain.'],
               [121, 'Each eye of a dragonfly has about 30,000 lenses.'],
               [122, 'Beards have a health-benefit effect. They prevent pollen from entering the mouth so that the possibility of getting hay fever is decreased.'],
               [123, 'Beavers have orange teeth, as they contain a lot of iron. The mineral makes the teeth particularly resistant to external forces.'],
               [124, 'Gray whales exclusively mate in a threesome.'],
               [125, 'The average rent for a one room apartment in Manhattan is 3,400 dollars.'],
               [126, 'The most common zodiac sign among billionaires is Aquarius. The least common one is Cancer.'],
               [127, 'With 16 percent of total global production India is the world largest producer of milk in the world.'],
               [128, 'During World War II, the U.S. Army collaborated with Walt Disney to develop a gas mask that looked like Mickey Mouse, in order to make children less afraid of a poison gas attack.'],
               [129, 'Frederic Baur developed the boxing of Pringles Chips. After his death in 2008, his ashes were buried in a Pringles box.'],
               [130, 'In 1916, a law was submitted to the US Congress to stipulate that any declaration of war by the USA first had to be confirmed by a referendum and that anyone who voted “yes” would have to go to war themselves. However, the law was never passed.'],
               [131, 'If all the gold in the world was melted, a dice with an edge length of 66 feet would be the result.'],
               [132, 'Parkinson’s Law describes the fact that an employee needs as much time for a task as he has available for it.'],
               [133, 'Josef Stalin ordered at least 22 assassination attempts on the former Yugoslav President Josip Broz Tito. After his death, a letter to Stalin with the following words was discovered: “Stop sending people to kill me. If you don’t stop sending assassins, I will send one to Moscow and I will certainly not have to send a second one.”'],
               [134, 'Pingelap is a Western Pacific island atoll where two thirds of the inhabitants are color-blind.'],
               [135, 'On average, a raindrop reaches a speed of 21.7 miles per hour.'],
               [136, 'If you visit a Jewish grave, it is common practice to leave a small stone as a symbol of mourning and remembrance. The tradition dates back to a time when all Jewish graves were still in the desert. In order to prevent scavengers from digging up the corpses, the mourners erected pyramids of small stones.'],
               [137, 'The “Kumbh Mela” in India is not just the biggest festival in Hinduism but also the biggest event in general. The range of estimated attendees is between 30 million to 60 million people. It’s so large that it can even be seen from space.'],
               [138, 'Since 1944, Iceland does not have its own army, and have not been attacked by other countries since.'],
               [139, 'Taxis in New York City were used to be red and green. In 1912 the city adopted the yellow colour from a number of other cities throughout the United States.'],
               [140, 'Unlike other cats of prey, the snow leopard is not aggressive towards humans. To this day, there has not been a single known case in which a snow leopard attacked a human.'],
               [141, 'In 1993, Canadian lawyer Garry Hoy wanted to prove to a group of visitors that the glass in the Toronto Dominion Centre was unbreakable. To demonstrate this, he jumped against the glass – which thereupon broke out of its frame and plummeted downwards together with Garry Hoy. Hoy died, but the pane of glass remained intact, even after the fall.'],
               [142, 'Foxes use the Earth’s magnetic field to estimate distances.'],
               [143, 'At its widest point, from Colombia all the way to Indonesia, the Pacific Ocean is wider than the moon. This expanse of ocean is 12,300 miles across, which is more than five times the diameter of the moon.'],
               [144, 'The modern look of the U.S. flag was designed by a school child from Ohio as a school project. His teacher gave him a B-.'],
               [145, 'There are an estimated 500 million dogs on our planet.'],
               [146, 'R2-D2 from Star Wars is called C1-P8 in Italy.'],
               [147, 'US President John F. Kennedy was a passionate smoker. In 1962, he instructed his press officer to buy 1,000 Cuban cigars for him. Shortly after receiving the cigars, he went on to pass a law prohibiting the import of communist goods into the United States.'],
               [148, 'Although India is the 7th largest country in the world it has just one time zone.'],
               [149, 'Russian man, Valery Spiridonov was alleged to be the first human to receive a head transplant. His head was to be transplanted to a new body, but he decided against it after a long hesitation. Meanwhile, a Chinese man that hasn’t been named is to take his place.'],
               [150, ' Babies are not able to taste salt until they are four months old.'],
               [151, 'The constitution of the United Kingdom is not codified in one document, like the Constitution of the United States of America. However, there are a lot of separate rules and laws recognised as holding constitutional value.'],
               [152, 'The likelihood of getting bitten by a human in New York is higher than the likelihood of getting bitten by a shark in the sea. '],
               [153, 'The International Space Station is the most expensive object ever made by humans. It has cost 160 billion dollars so far.'],
               [154, 'Japanese shops have small balls filled with orange die in their tills. In the event of a theft, the store staff can throw the balls at the robber, who is then marked with the orange color for the police.'],
               [155, 'Because emus and kangaroos are not able to walk backwards, they are officially referred to as heraldic animals of Australia. '],
               [156, 'In the movie “Halloween” the villain Michael Myers wears a mask. In order to save production costs, they bought a Captain Kirk mask and simply painted it over.'],
               [157, 'During the first days in space, astronauts often suffer from space sickness. Since all bodily fluids are redistributed in weightlessness and the sense of balance is impaired, important tasks such as outboard work are not carried out in the first days of a space mission. There would be an acute risk of the astronauts throwing up in their suits.'],
               [158, 'The Bluetooth logo is composed of the old Nordic runes for H and B, which were the initials of Viking king Harald Bluetooth. He was known for his overwhelming communication skills.'],
               [159, 'Most streets in Japan have no name.'],
               [160, 'The Wasaga beach in Canada is the longest fresh water beach in the world.'],
               [161, 'Before there were trees on the earth, our planet was covered by giant mushrooms.'],
               [162, 'At least 50 percent of the oxygen in our atmosphere is produced by phytoplankton in the oceans and not by land plants. Due to the rising sea temperatures, however, the phytoplankton population continues to decline.'],
               [163, 'An ostrich can run a marathon in less than 60 minutes.'],
               [164, 'Between 2011 and 2013, McDonald’s has opened one branch a day in China.'],
               [165, 'The human circadian rhythm is better suited to life on Mars than on Earth.'],
               [166, 'All of our school textbooks show the solar system with the planets close enough to fit on one page. In actuality if you were to draw the solar system to scale and the earth was the size of a pea on paper Jupiter would be over 984 feet away and Pluto would be one and a half mile away. The nearest star would be 9,940 miles away on paper.'],
               [167, 'Due to the decline of the lion population, there are now more lion statues worldwide than real lions.'],
               [168, 'Female skunks are able to influence the development of their embryos, in order to delay birth in times of food shortages.'],
               [169, 'In the 90s, 50 percent of all CDs produced were the free AOL Internet CD.'],
               [170, 'In 1990, the Michigan police organized a wedding of two of their undercover agents. Numerous drug dealers have been invited and were arrested during the wedding ceremony.'],
               [171, 'Only five percent of all humans have red hair.'],
               [172, 'Tesla founder Elon Musk barely escaped death in 2000 after contracting malaria in Brazil.'],
               [173, 'Scientists have demonstrated that cats have the same brain patterns as humans have during sleep. It is therefore assumed that cats can dream.'],
               [174, 'Some roads in Australia are so long that the Australian state counteracts the risk of fatigue by playing little trivia games with the drivers along the side of the road.'],
               [175, 'For every episode of “The Simpsons” the producers needed six to nine months.'],
               [176, 'During the Second World War, the city of Constance was largely spared from Allied bombing raids. Unlike other German cities, Constance did not cut off electricity at night. Allied pilots could therefore hardly distinguish the city from neighboring Switzerland, where the lights also remained on at night. In order to avoid mistakes, no bombs were dropped in the region.'],
               [177, 'In 1975, the American Gary Dahl sold so-called “Pet Rocks”. These were just common pebbles, but Dahl marketed them like pets. Within a very short time, a big hype arose about the stones, quickly making Dahl a millionaire. Only one year later, however, the interest quickly subsided again.'],
               [178, 'Of all the countries that celebrate an Independence Day, 26 became independent of France.'],
               [179, 'For years, Liechtenstein and Haiti had the same flag, which was only noticed when the two nations met at the 1936 Olympic Games. A year later, the flag of Liechtenstein was therefore adorned with the symbol of a golden princely hat.'],
               [180, 'There are about nine million people in a prison around the world. 25 percent of them come from the USA.'],
               [181, 'More than 50 percent of the world’s population has never received a phone call.'],
               [182, 'The average person watches their favorite movie 29 times in their lifetime.'],
               [183, 'Termites eat their food at double the speed when heavy metal is played.'],
               [184, 'Behind Lincoln’s face in Mount Rushmore, there is a secret chamber where memorabilia of the most important historical events in the USA are kept. The room is not accessible to tourists.'],
               [185, 'It is estimated that 7,000 people die every year because the handwriting of the treating doctor was not legible.'],
               [186, 'The inventor of “Spongebob” Stephen Hillenburg was a marine biologist, which is why he chose the deep sea as the setting for his cartoon series.'],
               [187, 'Argentina is the fifth largest producer of wine in the world.'],
               [188, 'Seen chronologically, Cleopatra was closer to the moon landing than to the construction of the pyramids.'],
               [189, 'Manhattan comes from a word in the Lenape language and means “Island of many hills”.'],
               [190, 'Brazil is also home to far more species of primates than any other nation.'],
               [191, 'Blue whales are the heaviest animals in the history of the earth. With a length of up to 110 feet, they weigh a total of 150 tons.'],
               [192, 'Although Rwanda is listed as #46 least developed country in the world it has a better gender equality than the USA.'],
               [193, 'Slugs are able to sleep three consecutive years.'],
               [194, 'Kopi luwak is the most expensive coffee in the world. It is produced by feeding the beans to civets, which break down the bitter substances in the beans during their digestive process. The otherwise intact beans are collected after excretion and prepared for sale.'],
               [195, 'At minimum, a person only needs one kidney with a capacity of at least 75 percent to survive.'],
               [196, 'Students get better test results when looking at a green landscape during the test.'],
               [197, 'Brazilian prisoners can reduce their sentence by four days for every book they read, up to 48 days per year. However, it is required that the prisoner writes a book report as a proof of reading the book. The idea is to help inmates be better prepared for success when they reintegrate with the outside world.'],
               [198, 'The “Fallen Astronaut Sculpture” is the only work of art on the moon so far. It was created by Belgian artist Paul Van Hoeydonck and brought to the moon during the Apollo 15 mission in 1971. It commemorates the 14 astronauts who died prior to the Apollo 15 mission.'],
               [199, 'Instead of “LOL” people in France say MDR for “mort de rire”, which means laughing to death.'],
               [200, 'When Wilhelm Röntgen discovered a new form of radiation, he could not think of a suitable name for this phenomenon, so he simply called it X-radiation. This is the reason why to this day the rays are called “X rays” in English, while in German-speaking countries they are known as “Röntgen rays”.'],
               [201, 'According to the Bible, the chicken came before the egg (Genesis 1:20-22).'],
               [202, 'The dance style “Daggering” was forbidden on Jamaican television, as it lead to numerous penis fractures during the dancing.'],
               [203, 'When Alexander Graham Bell, the inventor of the telephone, died in 1922, all telephones in the United States and Canada were switched off for one minute on 4 August of that year.'],
               [204, 'In the time since Pluto was discovered approximately 75 years ago, it has only traveled one third of its way around the sun.'],
               [205, 'In war times significantly more boys than girls are born. This is called the “Returning Soldier Syndrome”.'],
               [206, 'It is impossible to move your eyes smoothly from left to right or vice versa without interruption, unless you are following a moving object. The reason for this is that the eye always jumps from focus point to focus point with every movement.'],
               [207, 'Jack Daniel’s now also sells whiskey-flavored coffee beans.'],
               [208, 'As the earth rotates slower around the sun from year to year, 2016 was one second longer than 2015.'],
               [209, 'The Vatican has its own telephone company, its own radio station, its own TV station, its own stamps, its own currency and its own army.'],
               [210, 'The entire human population could live in New Zealand, and the population density would still be lower than that of Manhattan in New York.'],
               [211, 'One fifth of all people use their smartphone during sex.'],
               [212, 'The 100 richest people in the world earned so much money last year that they could end global poverty four times over.'],
               [213, 'The average thickness of ice in Antarctica is about 1 mile (1.6 km).'],
               [214, 'The suicide rate in Japan is 60 percent above the global average. This is why workshops teaching people to express their feelings are becoming more and more popular in the country.'],
               [215, 'France was the first country to introduce the vehicle license plate on August 14, 1893.'],
               [216, 'New York City got its nickname “Big Apple” from a local newspaper in the 1920s. The phrase “Big Apple” was used to describe a big money prize at important horse races held around the city.'],
               [217, 'Marvel originally was named “Timely Comics”.'],
               [218, 'There are more people living in California than in Canada.'],
               [219, 'In the U.S., the probability of suicide is twice the rate of an assassination by a third party.'],
               [220, 'If the US state of California were a separate country, it would be the fifth largest economy in the world and thus economically larger than France or Great Britain.'],
               [221, 'The Caspian Sea is the largest lake on earth. The largest freshwater lake in the world on the other hand is Lake Superior between Canada and the United States.'],
               [222, 'The monument of Stonehenge claimed to be one of the oldest monuments in the world. Scientists believe that the object was built over 4,500 years ago.'],
               [223, 'American school buses are yellow because a study from the 1930s showed that people can perceive the color yellow from a very long distance and therefore the risk of the school buses being involved in accidents decreases.'],
               [224, '“Trimethylaminuria” is a metabolic disease that causes the patient to smell strongly of old fish.'],
               [225, 'On average, there are 88.8 weapons per 100 U.S. citizens.'],
               [226, 'The Golden Gate Bridge has to be painted regularly. The salt water corrodes the paint so fast, that one has to start repainting the bridge as soon as one is finished painting it.'],
               [227, 'The South African rock hyrax is only 20 inches tall, weighs about 8.8 pounds and looks like a big guinea pig. Nevertheless, its closest relative is the elephant.'],
               [228, 'Nintendo originally did not develop consoles and video games, but rather started off producing playing cards.'],
               [229, 'At the age of five years and eleven months, Ayan Qureshi passed the “Microsoft Certified Professional Test”, making him the youngest computer specialist in the world.'],
               [230, 'The brain takes about 0.6 seconds to choose the right word for a term.'],
               [231, 'Basketball was invented by Dr. James Naismith, a Canadian physical educator, while he was looking for a game that can be played indoors during winter.'],
               [232, 'The longest street in the world connects Alaska with the south of Argentina. It has a length of approximately 18,641 miles and crosses 17 states, six time zones and four climate zones.'],
               [233, 'More Jewish people live in New York City than in any other city outside of Israel.'],
               [234, 'Approximately 200,000 new people are born each day.'],
               [235, 'Only 14 percent of all billionaires have no degree.'],
               [236, 'After the Japanese attack on Pearl Harbor during World War 2, Canada declared war on Japan one day earlier than the USA did.'],
               [237, 'The Perito Moreno Glacier in Patagonia, Argentina is the third largest reserve of fresh water in the world.'],
               [238, 'Each year around 1,000 people die because they are struck by lightning.'],
               [239, 'Sleeping on your belly can lead to crazier, creepier and more sexual dreams.'],
               [240, 'Canada was the third country sending a satellite to space, after USA and USSR.'],
               [241, 'In the USA, a slave from 1850 by today’s standards, would cost 1,000 dollars.'],
               [242, 'The largest amount of money stolen from a bank by robbers occurred in August 2005 in Brazil. A gang of up to 10 people dug a 256-foot long tunnel in Fortaleza to steal nearly $70 million. '],
               [243, 'Although during the Great Fire of London the homes of 70,000 of the city’s 80,000 inhabitants were destroyed only six verified deaths were officially recorded.'],
               [244, 'Reed Hasting, the founder of Netflix, came up with the idea for the streaming service after forgetting to return a rental DVD and paying $40 for it.'],
               [245, 'A total of 90% of Canada is uninhabited.'],
               [246, 'Historical finds prove that man sailed on ships as early as 6,000 years BC. The first traces of wheels, however, only date back to 4,000 years BC, meaning that ships seem to have been invented before the wheel.'],
               [247, 'A study from 2003 came to the conclusion that French people, among all nations, have the most frequent sex.'],
               [248, 'On 24 February 1891, the “United States of Brazil” were founded, and the name of the country lasted for almost 40 years. So at the time, the American continent was home to not only the USA, but also the USB.'],
               [249, 'In the Turkish village Halfeti, completely black roses grow each summer.'],
               [250, 'The Empire State Building generates more revenue from the observation deck than from its renting income.'],
               [251, 'Due to earthquakes and tsunamis, Tokyo was destroyed and rebuilt on average every five years between 1608 and 1945.'],
               [252, 'Brooklyn “Brookie” Supreme is considered the largest horse to ever have existed. It was almost 6.6 feet tall and weighed over 1.5 tons.'],
               [253, 'At the beginning of the 20th century, horses created so much dirt with their excrements that cars were regarded as the “green” alternative.'],
               [254, 'The number of all possible Sudoku puzzles with a 9×9 field is 6,670,903,752,021,072,936,960, which is about 6.7 sextillion.'],
               [255, 'Sharks and rays are the only animals that cannot develop cancer.'],
               [256, 'Since 1896, soccer fields in Germany have to be free of trees.'],
               [257, 'The shortest commercial flight lasts only 47 seconds and brings people in Scotland from the Westray Island to Papa Westray Island.'],
               [258, 'The intelligence of a child is primarily determined by its mother.'],
               [259, 'In 2014 a woman was saved from her burning house. She then realized she had forgot her mobile phone in the house, ran back into her home and died.'],
               [260, 'In the history of the United States there have been 17 Americans who ran a marathon in less than two hours and ten minutes. In October 2011 this was achieved by 32 Kenyans. '],
               [261, 'If you trace your family tree back 25 generations, you will have 33,554,432 direct ancestors. Assuming no incest was involved.'],
               [262, 'A 20 second hug increases the oxytocin level of people so much that afterwards there is a much greater trust between them.'],
               [263, 'The first traffic light was installed in London outside the Houses of Parliament in 1868. Unfortunately, it exploded very soon, killing a policeman.'],
               [264, 'Queen Elizabeth uses her handbag to send secret signals to her employees. Changing the bag from one hand to the other, for example, constitutes a request to end the current conversation.'],
               [265, 'The Chancellor’s office in Berlin is known as the “washing machine” due to its shape of a washing machine.'],
               [266, 'Brazil is home to the largest population of Catholics. Approximately 120 million Catholics are living there.'],
               [267, 'The entire border between the United States and Canada consists of a cleared strip of forest with a width of approximately 20 feet.'],
               [268, 'Jabbar Collins was imprisoned for 16 years. During this time he read numerous law books and found a procedural error which led to his freedom and a compensation of ten million dollars.'],
               [269, 'On average, people laugh ten times a day.'],
               [270, 'A person has between 100,000 and 150,000 hairs on their head.'],
               [271, 'In 1952 Albert Einstein received the offer to become President of Israel. He refused.'],
               [272, 'Blind people have nightmares, and have them four times more often than normal seeing people do.'],
               [273, 'Robert Lane named his two sons “Winner” and “Loser”. Winner Lane turned criminal, while Loser Lane had a successful career at the NYPD.'],
               [274, 'Scientists at the Massachusetts Institute of Technology have developed a tattoo ink that changes color when a person is dehydrated or when his or her blood sugar level is too high.'],
               [275, 'During WW2, Hajimi Fuji volunteered for the kamikaze but was refused because he had a wife and two children. His wife then drowned her two young girls and herself.'],
               [276, 'sia has a larger surface area than the moon. While the surface of the moon measures only 14,645,698 square miles, Asia covers a total of 17,212,368 square miles.'],
               [277, 'Nearly one in five Germans regularly use a laptop on the toilet.'],
               [278, 'In France it is prohibited by law, to name a pig “Napoleon”.'],
               [279, 'A Scottish study found that most heart attacks happen on a Monday.'],
               [280, 'The Indian state railway company employs more than one million people. This makes the company the world’s largest employer in the world. '],
               [281, 'Karaoke is Japanese and means “empty orchestra”.'],
               [282, 'A study has shown that people with a lot of body hair have on average a higher IQ than people with less body hair.'],
               [283, 'The brain growth of early humans only began due to the increased protein intake from an increasingly meat-oriented diet.'],
               [284, 'It has been scientifically proven that yawning is more contagious in winter than in summer.'],
               [285, 'The color that the human eye perceives in complete darkness is called “Eigengrau” (German for “intrinsic gray”).'],
               [286, 'The country with the lowest population density is Mongolia. On average, there are only 4.9 people per square mile.'],
               [287, 'Australia produces around 1.3 billion liters of wine each year.'],
               [288, 'Being in love releases the same hormones that the use of cocaine releases.'],
               [289, 'In South Africa there is a bar in a 6,000 year old tree.'],
               [290, 'The moonwalk was not actually invented by Michael Jackson. Cab Calloway included similar movements in his performances as early as 1932. At that time, however, people called it “The Buzz”.'],
               [291, 'The word “gym” comes from Greek and translates to “place of the naked.”'],
               [292, 'The name “Lego” is derived from “Leg Godt”, which means “play well” in Danish.'],
               [293, 'Miguel Indurain, five times Tour de France winner, has a resting heart rate of 28 beats per minute.'],
               [294, 'The deepest known area of the Earth’s oceans is the Mariana Trench. It’s deepest point measures 11km.'],
               [295, 'According to the Global Age Watch Index 2014, Germany is the third best country on earth after Sweden and Norway, for humans to get as old as possible.'],
               [296, 'Leonid Rogozovy is the only human to do an appendectomy with local anaesthesia on himself.'],
               [297, 'The first Twitter user to reach more than a million followers was Ashton Kutcher.'],
               [298, 'Scientists assume that the face of the Sphinx was painted red.'],
               [299, 'The saying “Happy wife, happy life” has been scientifically proven. Men whose wives are happy are also happier themselves.'],
               [300, 'Due to plate tectonic movements, Australia migrates to the north by about 2.8 inches each year.'],
               [301, 'The first name of Master Yoda from Star Wars is “Minch”.'],
               [302, 'The Islamic movement “Moro Islamic Liberation Front” calls itself “MILF”.'],
               [303, 'February 29 was first introduced as a leap day by Julius Caesar in 45 BC.'],
               [304, 'Star Trek was the first TV series to show a kiss between a white man and a black woman on TV.'],
               [305, 'The Moon is drifting approximately 1.5 inches (3.8 cm) away from Earth every year and it is estimated that it will continue to do so for around 50 billion years.'],
               [306, 'Because of pressure balance it is impossible to whistle in a space suit.'],
               [307, 'Hulk originally was meant to be a grey monster but as the printing works had problems to always use the identical shade of grey, the creators decided to turn Hulk green.'],
               [308, 'Retweets and Hashtags were not invented by Twitter, but were developed by users of the short message service and later integrated into the service as official functions.'],
               [309, 'Beer and all other alcoholic drinks with less than 10% alcohol in were not considered an alcoholic beverage in Russia until 2013.'],
               [310, 'An average cloud weighs about 1.5 million pounds.'],
               [311, 'The average Bugatti customer owns 84 different vehicles, three airplanes and a yacht.'],
               [312, 'You get a personalized card from the Queen if you reach your 100th birthday in the United Kingdom.'],
               [313, 'On average, children start lying at the age of four.'],
               [314, 'About 99,99999999999% of an atom is “nothing”. If one would eliminate the empty space of all atoms from the entire human race, the remaining mass would fit in a coffee mug.'],
               [315, 'The Romanian scientist Nicolas Minovici explored death by hanging and for his studies hanged himself from a gallows several times.'],
               [316, 'The Counter Strike team “Silver Snipers” consists of five members who are between 62 and 81 years old.'],
               [317, 'Jonas Salk refused to take out a patent on his polio vaccine. He commented that: “There is no patent. Could you patent the sun?”'],
               [318, 'September always begins on the same day of the week as December.'],
               [319, 'The thermometer was invented in Italy.'],
               [320, 'Canada became a country on July 1st, 1867 when the British Parliament passed the British North America Act.'],
               [321, 'In ancient Babylon it was tradition for every woman to go to the Temple of Aphrodite at least once in her life to have sex with a stranger.'],
               [322, 'The weight of the sun is approximately 1.989.000.000.000.000.000.000.000.000.000 kg.'],
               [323, 'Neither Hollywood nor Bollywood produced the most movies per year. It is Nollywood in Nigeria, where about 2,000 movies are finished a year.'],
               [324, '“Nomophobia” describes the fear of not being available via mobile phone.'],
               [325, 'A 60-year-old “Macallan Valerio Adami 1926” whiskey was auctioned in 2018 for 848,750 pounds, marking the highest price ever spent on a single bottle of whiskey.'],
               [326, 'In Japan, there is an office tower in which a highway runs though, between the fifth and the seventh floors.'],
               [327, 'Most serial killers are born in November.'],
               [328, 'The Pomato is a hybrid between a tomato and a potato. The plant produces both tomatoes and potatoes.'],
               [329, 'In Amsterdam there is a gym where you can train naked.'],
               [330, 'Argentina is currently the third-largest beef exporter in the world after Australia and Brazil.'],
               [331, 'In 2017, researchers discovered the largest dinosaur footprint to date in Western Australia. The footprint is over 5 feet long and is said to be over 130 million years old.'],
               [332, 'When James Cameron was in a Roman hospital due to food poisoning he had a nightmare about a robot from the future trying to kill him. From this idea he created the script for “Terminator”.'],
               [333, 'There is a programming language called ArnoldC, which consists only of quotes by Arnold Schwarzenegger.'],
               [334, 'The largest land animal permanently living in Antarctica is only 0.24 inches long. It is the wingless mosquito species “Belgica antarctica”.'],
               [335, 'If 57 people are gathered in one room, the likelihood of two of the people having their birthday on the same day, is about 99 percent.'],
               [336, 'Almost all windmills in the world rotate counterclockwise, while almost all wind turbines in the world rotate clockwise.'],
               [337, 'The equal sign “=” was invented in 1557 by Robert Recorde.'],
               [338, 'In Iceland, Greenland and the Antarctic there are no ants.'],
               [339, 'The construction of the Titanic cost seven million dollars. The film starring Leonardo DiCaprio cost 200 million dollars to produce.'],
               [340, 'With about one billion people or 15 percent of the world’s population Africa is the second most populous continent.'],
               [341, 'It takes 40 minutes to cook an ostrich egg.'],
               [342, 'The US aircraft carrier USS Abraham Lincoln is operated by nuclear power and therefore only needs to be “refueled” every 25 years.'],
               [343, 'Pumba from “The Lion King” was the first Disney character who was allowed to fart.'],
               [344, 'The first hard disk for Apple II had a capacity of five megabyte.'],
               [345, 'The starting melody of Windows was composed on a Mac.'],
               [346, 'The first printed book was published in German. It was the Bible.'],
               [347, 'Popcorn became a popular cinema snack in the United States during the global economic crisis because it was so cheap.'],
               [348, '“May I have a large container of coffee”. If you count the number of letters of every word in this sentence you get a good approximation for pi.'],
               [349, 'To date, it is not clear why people and other animals need sleep. There are many theories, but even experts are uncertain about their accuracy.'],
               [350, 'The colder your bedroom is, the higher is the likelihood of having a nightmare.'],
               [351, 'Regular sex can relieve nasal congestion and help treat asthma and hay fever.'],
               [352, 'Michael James Massimino, an astronaut who has made several guest appearances in “The Big Bang Theory”, was the first person to tweet from space.'],
               [353, 'The Tammar wallaby has a weight of only one gram at birth.'],
               [354, 'Penguins can jump six feet high.'],
               [355, 'On the occasion of the new Star Wars Movie “The Force Awakens” the weirdest products were sold under the “Star Wars” trade mark. Including a knife block, oranges, mascara and special “Yoda water”. '],
               [356, '100,000,000,000 tons of dynamite would have to be detonated every second to match the energy produced by the sun.'],
               [357, 'The letters “J” and “Q” do not occur in the periodic table of elements.'],
               [358, 'When the Egyptians built the pyramids, there were still mammoths roaming the earth.'],
               [359, 'McDonald’s Big Mac is used as an economic index to compare the purchasing power between different currencies and countries.'],
               [360, 'In Finland every traffic ticket is based on your personal income. The highest fine ever paid for speeding was 100,000 Euros.'],
               [361, 'McDonald’s is the biggest customer of Coca Cola.'],
               [362, 'The movie “French Kiss” is called “English Kiss” in France.'],
               [363, 'Human fingers are so sensitive that they can feel objects of 13 nanometers in size. This means that if one finger was the size of the earth, it could feel the difference between a house and a car. '],
               [364, 'A study has shown that the brain can remember things on paper more easily than their digital equivalent.'],
               [365, 'Women blink more frequently than men.']
]

mydb = mysql.connector.connect(
  host="localhost",
  user="holly",
  password="Hollyisthebest!",
  database="ElephantFacts"
)

print(mydb)

cursor = mydb.cursor()


for i in range(len(listOfFacts)):
    sql = "DELETE FROM general WHERE ID = '" + str(i + 1) + "'"

    cursor.execute(sql)

    mydb.commit()

cursor.execute("SELECT * FROM general")

result = cursor.fetchall()

for row in result:
    print(row)

cursor.execute("DELETE FROM general")


sql = "INSERT INTO general (ID, fact) VALUES (%s, %s)"
for val in listOfFacts:
    cursor.execute(sql, val)

    mydb.commit()

cursor.execute("SELECT * FROM general")

result = cursor.fetchall()

for row in result:
    print(row)
